import getConfigDefaults from '../utils/get-config-defaults.js';
import getEngineConfig from '../utils/get-engine-config.js';
import getCacheDir from '../utils/get-cache-dir.js';
import loadEnv from '../utils/load-env.js';
import loadConfigFiles from '../utils/load-config-files.js';
import loadEnvPluginConfig from '../utils/load-env-plugin-config.js';
import legacyMerge from '../utils/legacy-merge.js';
import stripEnv from '../utils/strip-env.js';
import tryConvertJson from '../utils/try-convert-json.js';

export const defaults = (...args) => getConfigDefaults(...args);
export const getEngineConfigFn = (...args) => getEngineConfig(...args);
export {getEngineConfig};
export const getOclifCacheDir = (...args) => getCacheDir(...args);
export const loadEnvs = (...args) => loadEnv(...args);
export const loadFiles = (...args) => loadConfigFiles(...args);
export {loadEnvPluginConfig};
export const merge = (...args) => legacyMerge(...args);
export {stripEnv};
export {tryConvertJson};
